### ISSUE TITLE
Color Grading still slightly off

### ISSUE THREAD

**Issue by piotr-j** [voodoosoft/gameroots#1]
Its very subtle, but its there. Probably most visible in the orange tint bottom left, and dark tint lower centre.
[CG Off](https://imgur.com/NsEJAXC)
[CG On](https://imgur.com/21zzDEI)
Not certain if it is fixable.

**Comment by voodoosoft** [comment]
Probably not fixable with this limited number of lookups. But good enough for the gaming use case.
